export const lineGraphData = [
  { id: 1, week: "Week 1", day: "Monday" },
  { id: 2, week: "Week 1", day: "Tuesday" },
  { id: 3, week: "Week 1", day: "Wednesday" },
  { id: 4, week: "Week 1", day: "Thursday" },
  { id: 5, week: "Week 1", day: "Friday" },
  { id: 6, week: "Week 1", day: "Monday" },
  { id: 7, week: "Week 1", day: "Wednesday" },
];

export const recentClient = [
  {
    id: 1,
    name: "John Doe",
    purpose: "Medicine for pregnant",
  },
  {
    id: 2,
    name: "Jane Smith",
    purpose: "Vaccination",
  },
  {
    id: 3,
    name: "Alice Johnson",
    purpose: "General Checkup",
  },
  {
    id: 4,
    name: "Michael Brown",
    purpose: "Prescription Refill",
  },
  {
    id: 5,
    name: "Emily Davis",
    purpose: "Lab Tests",
  },
];

// data.js

export const users = [
  {
    id: 1,
    name: "John Doe",
    email: "john.doe@example.com",
    avatar: "https://i.pravatar.cc/150?img=1",
    role: "Developer",
    team: "Frontend",
    status: "active",
  },
  {
    id: 2,
    name: "Jane Smith",
    email: "jane.smith@example.com",
    avatar: "https://i.pravatar.cc/150?img=2",
    role: "Designer",
    team: "UI/UX",
    status: "paused",
  },
  {
    id: 3,
    name: "Alice Johnson",
    email: "alice.johnson@example.com",
    avatar: "https://i.pravatar.cc/150?img=3",
    role: "Project Manager",
    team: "Management",
    status: "vacation",
  },
  {
    id: 4,
    name: "Michael Brown",
    email: "michael.brown@example.com",
    avatar: "https://i.pravatar.cc/150?img=4",
    role: "Backend Developer",
    team: "Backend",
    status: "active",
  },
  {
    id: 5,
    name: "Emily Davis",
    email: "emily.davis@example.com",
    avatar: "https://i.pravatar.cc/150?img=5",
    role: "QA Engineer",
    team: "Quality Assurance",
    status: "paused",
  },
];

export const workersData = [
  {
    firstName: "John",
    lastName: "Doe",
    sex: "Male",
    age: 30,
    address: "123 Elm Street, Springfield",
    birthdate: "1994-05-15",
    placeAssigned: "Warehouse A",
    username: "john_doe",
  },
  {
    firstName: "Jane",
    lastName: "Smith",
    sex: "Female",
    age: 28,
    address: "456 Oak Avenue, Springfield",
    birthdate: "1996-08-22",
    placeAssigned: "Office B",
    username: "jane_smith",
  },
  {
    firstName: "Alice",
    lastName: "Johnson",
    sex: "Female",
    age: 34,
    address: "789 Pine Road, Springfield",
    birthdate: "1990-01-10",
    placeAssigned: "Site C",
    username: "alice_j",
  },
  {
    firstName: "Bob",
    lastName: "Williams",
    sex: "Male",
    age: 45,
    address: "321 Maple Street, Springfield",
    birthdate: "1979-11-30",
    placeAssigned: "Warehouse A",
    username: "bob_williams",
  },
  {
    firstName: "Charlie",
    lastName: "Brown",
    sex: "Male",
    age: 25,
    address: "654 Birch Lane, Springfield",
    birthdate: "1999-04-20",
    placeAssigned: "Office B",
    username: "charlie_b",
  },
  {
    firstName: "Diana",
    lastName: "Prince",
    sex: "Female",
    age: 32,
    address: "987 Cedar Street, Springfield",
    birthdate: "1992-07-14",
    placeAssigned: "Site C",
    username: "diana_prince",
  },
  {
    firstName: "Ethan",
    lastName: "Hunt",
    sex: "Male",
    age: 38,
    address: "159 Willow Way, Springfield",
    birthdate: "1986-02-05",
    placeAssigned: "Warehouse A",
    username: "ethan_hunt",
  },
  {
    firstName: "Fiona",
    lastName: "Gray",
    sex: "Female",
    age: 29,
    address: "753 Elmwood Drive, Springfield",
    birthdate: "1995-09-25",
    placeAssigned: "Office B",
    username: "fiona_gray",
  },
  {
    firstName: "George",
    lastName: "Lucas",
    sex: "Male",
    age: 55,
    address: "246 Oakwood Road, Springfield",
    birthdate: "1969-03-30",
    placeAssigned: "Site C",
    username: "george_lucas",
  },
  {
    firstName: "Hannah",
    lastName: "Montana",
    sex: "Female",
    age: 22,
    address: "135 Spruce Street, Springfield",
    birthdate: "2002-06-16",
    placeAssigned: "Warehouse A",
    username: "hannah_m",
  },
];

//client dummy data
export const clientList = [
  {
    name: "John Doe",
    phoneNumber: "09999999999",
    profile: "General Client",
    category: "PRENATAL & POSPARTUM CARE",
  },
  {
    name: "Jane Smith",
    phoneNumber: "09999999999",
    profile: "PWD",
    category: "PERSON WITH DISABILITY (PWD)",
  },
  {
    name: "Alice Johnson",
    phoneNumber: "09999999999",
    profile: "Family Planning Advocate",
    category: "WRA (15-49 YEARS OLD) FAMILY PLANNING",
  },
  {
    name: "Mark Lee",
    phoneNumber: "09999999999",
    profile: "Hypertension Patient",
    category: "HYPERTENSIVE AND TYPE 2 DIABETES MELITUS",
  },
  {
    name: "Emily Davis",
    phoneNumber: "09999999999",
    profile: "Adolescent",
    category: "10-19 YEARS OLD (ADOLESCENTS)",
  },
  {
    name: "Peter Clark",
    phoneNumber: "09999999999",
    profile: "Nutrition Specialist",
    category: "0-59 MONTHS OLD CHILDREN - NUTRITION SERVICES",
  },
  {
    name: "Helen Carter",
    phoneNumber: "09999999999",
    profile: "Senior Citizen",
    category: "SENIOR CITIZEN(60 YEARS OLD ABOVE)",
  },
  {
    name: "Michael Thompson",
    phoneNumber: "09999999999",
    profile: "Filariasis Program Member",
    category: "FILARIASIS PROGRAM SERVICES",
  },
  {
    name: "Sarah Green",
    phoneNumber: "09999999999",
    profile: "School-Aged Child",
    category: "5-9 YEARS OLD CHILDREN (SCHOOL AGED CHILDREN)",
  },
  {
    name: "Kevin White",
    phoneNumber: "09999999999",
    profile: "Infant",
    category: "0-11 MONTHS OLD INFANTS - IMMUNIZATION SERVICES",
  },
  {
    name: "Laura Martinez",
    phoneNumber: "09999999999",
    profile: "Schistosomiasis Patient",
    category: "SCHISTOSOMIASIS PROGRAM SERVICES",
  },
  {
    name: "David Black",
    phoneNumber: "09999999999",
    profile: "Current Smoker",
    category: "CURRENT SMOKERS",
  },
  {
    name: "Olivia Brown",
    phoneNumber: "09999999999",
    profile: "Vision Screening Participant",
    category: "0-59 YEARS OLD SCREENED FOR VISUAL ACTIVITY",
  },
];

//unused
export const clientData = [
  {
    name: "John Doe",
    forms: [
      "PRENATAL & POSPARTUM CARE",
      "SENIOR CITIZEN(60 YEARS OLD ABOVE)",
      "PERSON WITH DISABILITY (PWD)",
    ],
    address: "123 Main St, Cityville",
    phone: "09123456789",
    birth: "1990-01-15",
    philhealthId: "PH-123456789",
    dateRegistered: "2023-09-01",
    categoryType: "pregnant",
    medicationForm: {
      page1: {
        field1: "field1",
        field2: "field2",
        field3: "field3",
        field4: "field4",
        field5: "field5",
      },
      page2: {
        field1: "field1",
        field2: "field2",
        field3: "field3",
        field4: "field4",
        field5: "field5",
      },
    },
  },
  {
    name: "Jane Smith",
    forms: [
      "HYPERTENSIVE AND TYPE 2 DIABETES MELITUS",
      "SENIOR CITIZEN(60 YEARS OLD ABOVE)",
      "PERSON WITH DISABILITY (PWD)",
    ],
    address: "456 Oak St, Townsville",
    phone: "09234567890",
    birth: "1985-04-22",
    philhealthId: "PH-987654321",
    dateRegistered: "2023-08-15",
    categoryType: "vaccination",
    medicationForm: {
      page1: {
        field1: "field1",
        field2: "field2",
        field3: "field3",
        field4: "field4",
        field5: "field5",
      },
      page2: {
        field1: "field1",
        field2: "field2",
        field3: "field3",
        field4: "field4",
        field5: "field5",
      },
    },
  },
  {
    name: "Michael Johnson",
    forms: [
      "FILARIASIS PROGRAM SERVICES",
      "SENIOR CITIZEN(60 YEARS OLD ABOVE)",
      "PERSON WITH DISABILITY (PWD)",
    ],
    address: "789 Pine St, Villagetown",
    phone: "09345678901",
    birth: "1995-07-10",
    philhealthId: "PH-456123789",
    dateRegistered: "2023-07-22",
    categoryType: "general checkup",
    medicationForm: {
      page1: {
        field1: "field1",
        field2: "field2",
        field3: "field3",
        field4: "field4",
        field5: "field5",
      },
      page2: {
        field1: "field1",
        field2: "field2",
        field3: "field3",
        field4: "field4",
        field5: "field5",
      },
    },
  },
  {
    name: "Emily Davis",
    forms: [
      "5-9 YEARS OLD CHILDREN (SCHOOL AGED CHILDREN)",
      "-11 MONTHS OLD INFANTS - IMMUNIZATION SERVICES",
      "PERSON WITH DISABILITY (PWD)",
    ],
    address: "101 Maple Ave, Citytown",
    phone: "09456789012",
    birth: "1992-09-05",
    philhealthId: "PH-321654987",
    dateRegistered: "2023-06-18",
    categoryType: "lab tests",
    medicationForm: {
      page1: {
        field1: "field1",
        field2: "field2",
        field3: "field3",
        field4: "field4",
        field5: "field5",
      },
      page2: {
        field1: "field1",
        field2: "field2",
        field3: "field3",
        field4: "field4",
        field5: "field5",
      },
    },
  },
  {
    name: "Robert Brown",
    forms: [
      "CURRENT SMOKERS",
      "SENIOR CITIZEN(60 YEARS OLD ABOVE)",
      "PERSON WITH DISABILITY (PWD)",
    ],
    address: "202 Birch Blvd, Smallville",
    phone: "09567890123",
    birth: "1988-11-30",
    philhealthId: "PH-159753468",
    dateRegistered: "2023-05-30",
    categoryType: "prescription refill",
    medicationForm: {
      page1: {
        field1: "field1",
        field2: "field2",
        field3: "field3",
        field4: "field4",
        field5: "field5",
      },
      page2: {
        field1: "field1",
        field2: "field2",
        field3: "field3",
        field4: "field4",
        field5: "field5",
      },
    },
  },
];
